.buildkite/nodeTests, .buildkite/pipeline.yml, Dockerfile, docker-compose.yml
This is a proposal to use Buildkite for CI, which will allow for reproducible and parallel builds. Currently this will run alongside Travis while we try it out. The web platform team has had success with Buildkite, and we are willing to help folks integrate it into their workflows as we think it will bring improved productivity.
* Adds a dockerfile and docker-compose file for reproducible CI containers.
* Adds a buildkite pipeline for running linters and node tests in parallel.
Generates a build page that looks like this:
=> Use Buildkite and Docker for CI

.travis.yml, CHANGELOG, docs/api-reference/addons/polygon.md, docs/api-reference/euler.md, docs/api-reference/pose.md, docs/api-reference/spherical-coordinates.md, package.json, src/index.js, test/src/addons/polygon.spec.js, test/src/euler.spec.js, test/src/pose.spec.js, test/src/spherical-coordinates.spec.js, website/src/mdRoutes.js
This is an initial PR towards using `_` for marking experimental APIs. It raises a few questions:
* Should we doc these classes as `_Euler` etc?
* Or still doc them as `Euler (Experimental)` and just require that they be imported using underscore, e.g. `import {_Euler as Euler}`.
For some reason I seem to be in favor of the latter. Less impact on docs, ToCs etc.
@1chandu
=> Use underscore for experimental API

docs/api-reference/pose.md, src/pose.js, test/src/pose.spec.js
A `Pose` instance is serialized then deserialized when passed via `postMessage` between threads. This process removes all class methods and results in a plain object in the form of `{position: Array[3], orientation: Array[4]}`. It will be much easier to reconstruct the pose if the constructor understands this flatten format.
- `Pose.contructor` recognizes `position` and `orientation` from props
- Tests
=> Support reconstructing Pose from serialized/deserialized props

docs/api-reference/euler.md, src/euler.js, src/quaternion.js, test/src/euler.spec.js, test/src/matrix4.spec.js, test/src/quaternion.spec.js, test/webpack.config.js, yarn.lock
@xintongxia - by moving your nice quaternion to euler conversion function from 	`Quaternion.toEuler` into `Euler.fromQuaternion` we can significantly lower the bundle size impact of importing `Quaternion` without `Euler` from 32K to 9K, see below.
Do you think it is OK for the app to use `new Euler().fromQuaternion(q)` instead of `q.toEuler()`?
---
Running `yarn metrics` now measures tree shaken size of each class.
Before 
| Version        | Dist | Bundle Size      | Compressed     | Imports   |
| ---            | ---  | ---              | ---            | ---       |
| 2.3.0-beta.1   | es6  | 38KB (39175) KB  | 10KB (10715) KB     | all.js |
| 2.3.0-beta.1   | es6  | 32KB (33494) KB  | 9KB (9221) KB     | euler.js |
| 2.3.0-beta.1   | es6  | 32KB (33462) KB  | 9KB (9242) KB     | …
=> Decouple Quaternion from Euler to optimize tree-shaking

dev-docs/RFCs/README.md, dev-docs/RFCs/culling-module-rfc.md, dev-docs/RFCs/geometry-module-rfc.md, dev-docs/RFCs/geospatial-module-rfc.md, dev-docs/RFCs/math-monorepo-rfc.md, dev-docs/ROADMAP.md
Just FYI, initial versions of RFCs for new math.gl modules, will iterate on them together with documentation (which is  being built out in [loaders.gl docs](https://github.com/uber-web/loaders.gl/tree/master/docs/api-reference/math) as a temporary location).
=> Module RFCs

docs/README.md, docs/api-reference/geospatial/ellipsoid.md, docs/developer-guide/geospatial/geospatial.md, docs/table-of-contents.json, modules/core/src/lib/common.js, modules/core/test/lib/common.spec.js, modules/core/test/threejs-tests/index.js, modules/geospatial/README.md, modules/geospatial/package.json, modules/geospatial/src/constants.js, modules/geospatial/src/ellipsoid/ellipsoid.js, modules/geospatial/src/ellipsoid/helpers/ellipsoid-transform.js, modules/geospatial/src/ellipsoid/helpers/scale-to-geodetic-surface.js, modules/geospatial/src/index.js, modules/geospatial/src/type-utils.js, modules/geospatial/test/bench.js, modules/geospatial/test/ellipsoid/ellipsoid-transform.spec.js, modules/geospatial/test/ellipsoid/ellipsoid.bench.js, modules/geospatial/test/ellipsoid/ellipsoid.spec.js, modules/geospatial/test/index.js, modules/geospatial/test/type-utils.spec.js, test/bench.js, test/index.js
Adds a new module `@math.gl/geospatial` and seeds it with the central `Ellipsoid` class, which supports conversion between WSG84 cartesian and cartographic representations, as well as calculations of local transformations at given points on the ellipsoid.
This PR is part of the ongoing collaboration with Cesium on supporting 3D tiles in loaders.gl.
@lilleyse @loshjawrence
Close to 100% test coverage for the new module: <img width="592" alt="Screen Shot 2019-05-29 at 1 27 28 PM" src="https://user-images.githubusercontent.com/7025232/58588891-8b081e80-8215-11e9-86e2-42ea19c30052.png">
=> @math.gl/geospatial: new module, initial commit

modules/web-mercator/docs/api-reference/web-mercator-utils.md, modules/web-mercator/src/fly-to-viewport.js, modules/web-mercator/test/spec/fly-to-viewport.spec.js
Return `0` when transitioning to same viewport center.
=> [Fix] getFlyToDuration returns NaN when transitioning to same viewport center

modules/web-mercator/src/fit-bounds.js, modules/web-mercator/src/viewport.js, modules/web-mercator/src/web-mercator-utils.js, modules/web-mercator/src/web-mercator-viewport.js, modules/web-mercator/test/browser.js, modules/web-mercator/test/fp32-limits.js, modules/web-mercator/test/node.js, modules/web-mercator/test/spec/mercator-project-unproject.spec.js, modules/web-mercator/test/spec/normalize-viewport-props.spec.js, modules/web-mercator/test/spec/versus-mapbox/mapbox-transform.js, modules/web-mercator/test/spec/versus-mapbox/mapbox.js, modules/web-mercator/test/spec/versus-mapbox/versus-mapbox.spec.js, modules/web-mercator/test/spec/web-mercator-utils.spec.js, modules/web-mercator/test/spec/web-mercator-viewport.spec.js, modules/web-mercator/test/utils/test-utils.js, modules/web-mercator/test/webpack.config.js
These are changes that will make the web-mercator module pass the coming typescript introduction PR.
@Pessimistress Since this PR removes the unused scale parameter, I thought it might be good for you to give it a quick review, so I separated this from the other chunk of linter fixes.
=> web-mercator: pass typescript linter

docs/whats-new.md, lerna.json
The version situation was rather confusing, with no 3.1-release branch, and master lerna.json still on 3.1-alpha.
- Pushed a 3.1-release branch
- bumping lerna.json on master
=> Move master to 3.2-alpha track

modules/culling/docs/api-reference/axis-aligned-bounding-box.md, modules/culling/docs/api-reference/oriented-bounding-box.md, modules/culling/src/algorithms/bounding-box-from-points.d.ts, modules/culling/src/algorithms/bounding-box-from-points.js, modules/culling/src/index.d.ts, modules/culling/src/index.js, modules/culling/src/lib/axis-aligned-bounding-box.d.ts, modules/culling/src/lib/axis-aligned-bounding-box.js, modules/culling/src/lib/oriented-bounding-box.d.ts, modules/culling/src/lib/oriented-bounding-box.js, modules/culling/test/lib/axis-aligned-bounding-box.spec.js, modules/culling/test/lib/culling-volume.spec.js, modules/culling/test/lib/oriented-bounding-box.spec.js
- Add `distanceTo` and `distanceToSquare` methods to `AxisAlignedBoundingBox`
- Remove `AxisAlignedBoundingBox.fromPoints` (not documented, not used), add `makeAxisAlignedBoundingBoxFromPoints`
- Remove `OrientedBoundingBox.fromPoints` (not documented, not used)
- Fix errors in the documentation of `OrientedBoundingBox`
- Add documentation for `AxisAlignedBoundingBox`
=> Clean up bounding volume classes and docs

modules/web-mercator/src/fit-bounds.d.ts, modules/web-mercator/src/web-mercator-viewport.d.ts, modules/web-mercator/test/spec/fit-bounds.spec.js
It's expected to be a pair of pairs (`[[lon, lat], [lon, lat]]`), but the type is declared as `number`.
=> Fix the bounds type for FitBoundsOptions

modules/polygon/docs/api-reference/cut-polygon-by-grid.md, modules/polygon/docs/api-reference/cut-polygon-by-mercator-bounds.md, modules/polygon/src/cut-by-grid.d.ts, modules/polygon/src/cut-by-grid.js, modules/polygon/src/cut-by-mercator-bounds.d.ts, modules/polygon/src/cut-by-mercator-bounds.js, modules/polygon/src/lineclip.d.ts, modules/polygon/test/cut-by-grid.spec.js, modules/polygon/test/cut-by-mercator-bounds.spec.js
Adds an option `edgeTypes` to `cutPolygonByGrid` and `cutPolygonByMercatorBounds`. When enabled, the returned polygons contain an array of flags for each vertex:
+ `0` - the segment connecting this vertex to the next is inside the original polygon
+ `1` - the segment connecting this vertex to the next is on the border of the original polygon
This is needed by deck.gl to determine where to draw the sides of an extruded polygon.
A visualization of this feature: https://codepen.io/Pessimistress/pen/BaNOmKM?editors=0110
=> cutPolygonByGrid: add option to generate edge type flags

modules/polygon/src/cut-by-grid.js, modules/polygon/src/utils.js
Fix a bug where the length of `edgeType` does not match the number of vertices due to position deduplication.
=> [polygon] Fix edgeType bug

modules/proj4/docs/developer-guide/proj4-guide.md, modules/proj4/src/lib/proj4-projection.js
- Bind project/unproject methods to class
- Raise error when trying to use an undefined alias.
- Update docs to mention helpful epsg.io API: `https://epsg.io/4326.{proj4,wkt}`
=> Proj updates

modules/proj4/src/lib/proj4-projection.js, modules/proj4/test/lib/proj4-projection.spec.js
The Proj4Projection class currently doesn't bind (at least correctly) the `project` and `unprojection` wrappers around `proj4.forward` and `proj4.inverse`. This updates to bind them correctly to the class, and adds a test case
=> Bind project/unproject functions in Proj4Projection

modules/polygon/src/cut-by-grid.js
When `cutPolygonByGrid` processes polygon with holes, it may crash if a hole sticks outside of the outer polygon (outer polygon is in one cell but the hole is in two cells -> trying to add holes to non-existent parent). This could happen to ill-defined input or due to precision errors.
This fix adds safe guard against the above scenario by only deducing bounding box from the outer polygon.
=> [polygon] prevent cutPolygonByGrid crash in edge cases

website/gatsby-config.js
The "Get Started" link on the math.gl homepage currently links to
```
https://math.gl/modules/core/docs/developer-guide/core-overview
```
which doesn't exist.
=> Fix get started link

modules/polygon/src/lineclip.js, modules/polygon/test/cut-by-mercator-bounds.spec.js, modules/polygon/test/lineclip.spec.js
For https://github.com/visgl/deck.gl/issues/5123
`t * b[i] + (1 - t) * a[i]` has two precision roundings and `t * (b[i] - a[i]) + a[i]` has only one
=> [polygon] Improve subdivision precision

modules/core/src/classes/matrix4.d.ts
Matrix4 decomposition types are problematic, especially for default behaviour. When call `getScale` or `getTranslation`, the assumed returned type is `Matrix4` even if by implementation, it will return `number[]`. A `Matrix4` is only returned if the result parameter is of type `Matrix4` to begin with.
In this PR I attempt to correct this using overload. When no result parameter is given, we get `number[]` and when it is given, we get the same type as a result.
=> Fixes matrix4 decompose return types

modules/web-mercator/src/fit-bounds.js, modules/web-mercator/src/math-utils.js, modules/web-mercator/src/normalize-viewport-props.js, modules/web-mercator/src/web-mercator-utils.js
We had an error in prod today, in fit-bounds.js, `Object doesn't support property or method 'log2'`. 
Internet Explorer 11, Windows 10. 
Looks like another library had the same issue, and it's IE11 related. 
https://github.com/tangrams/tangram/issues/473
I couldn't tell if you intend to support IE 11, but the fix is so small I figured I'd send a PR anyway (by copying from the solution tangram used)
=> Handle missing log2 in IE 11

modules/culling/src/algorithms/bounding-box-from-points.js, modules/culling/test/lib/oriented-bounding-box.spec.js
`result.halfAxes.multiplyByScalar(scale);` - this line doesn't scale z axe. It is always 1.
New logic:
- Create scale Vector
- Create scale Matrix 3*3
- Fill main diagonal  using values from scale vector
- Multiply `halfSizes` on scale matrix
=> Boinding Box From Points - Fix for scaling method

modules/web-mercator/src/web-mercator-viewport.d.ts
The type definition for `WebMercatorViewport.getLocationAtPoint()` currently uses implicit any typing for `lngLat` and `pos`. This can cause TypeScript build errors if `noImplicitAny` is enabled and `skipLibCheck` is disabled:
```
node_modules/@math.gl/web-mercator/src/web-mercator-viewport.d.ts:149:23 - error TS7031:
Binding element 'lngLat' implicitly has an 'any' type.
149   getLocationAtPoint({lngLat, pos}): number[];
node_modules/@math.gl/web-mercator/src/web-mercator-viewport.d.ts:149:31 - error TS7031:
Binding element 'pos' implicitly has an 'any' type.
149   getLocationAtPoint({lngLat, pos}): number[];
```
This PR is a one-line change to add types for these arguments. The type signature for the function now matches the non-legacy …
=> Add a more detailed type definition for `WebMercatorViewport.getLocationAtPoint()`

modules/polygon/src/earcut.js, modules/polygon/src/index.js, modules/polygon/test/bench.js
https://github.com/visgl/loaders.gl/pull/1356 implemented polygon triangulation using earcut in loaders.gl however seems more natural to have earcut in math.gl, so as to allow other projects to import it if needed.
The implementation here is a straightforward copy-paste (and lint fix) of the original code with a simple optimization added to allow passing in areas (and thus windedness) of the rings. This allows the code to avoid recomputing the polygon areas if we already have them, which is often the case as they are computed during classification of the rings into exterior outlines and interior holes.
=> Add earcut

modules/web-mercator/docs/api-reference/web-mercator-viewport.md, modules/web-mercator/src/web-mercator-viewport.d.ts, modules/web-mercator/src/web-mercator-viewport.js, modules/web-mercator/test/spec/web-mercator-viewport.spec.js
Needed for react-map-gl to support Mapbox terrain. Names are aligned with deck.gl's `Viewport` class.
Change list:
- Add `position` to `WebMercatorViewport` constructor
- Add `meterOffset` field to viewport instance
- Docs
- Unit test
=> WebMercatorViewport supports camera meter offset

modules/culling/src/lib/algorithms/bounding-sphere-from-points.js, modules/culling/test/lib/algorithms/bounding-sphere-from-points.spec.js
The result of `makeBoundingSphereFromPoints` is dependent on the order of input points due to the incorrect population of min/max positions.
=> [fix] makeBoundingSphereFromPoints inconsistent result

modules/culling/src/lib/algorithms/bounding-box-from-points.js, modules/culling/test/index.js, modules/culling/test/lib/algorithms/bounding-box-from-points.spec.js
The funciton crashes when `points` are plain arrays instead of `Vector3`.
=> [fix] makeOrientedBoundingBoxFromPoints crash

modules/culling/src/lib/bounding-volumes/bounding-sphere.js, modules/culling/test/lib/bounding-volumes/bounding-sphere.spec.js
Currently yields NaN for points inside the sphere and incorrect result for points outside
=> [fix] BoundingSphere.distanceTo

modules/web-mercator/src/normalize-viewport-props.js, modules/web-mercator/test/spec/normalize-viewport-props.spec.js, yarn.lock
For https://github.com/visgl/react-map-gl/issues/1531
Before this change, clamped zoom/latitude values at low zoom are affected by their input due to precision loss in `WebMercatorViewport.project`/`unproject`. After this change, they are only determined by `height`.
=> [web-mercator] Improve viewport normalization

modules/core/package.json, modules/culling/package.json, modules/geospatial/package.json, modules/web-mercator/package.json, package.json, yarn.lock
Ref https://github.com/uber-web/math.gl/issues/252#issuecomment-934695063, https://github.com/toji/gl-matrix/issues/439. This is a quick fix to prevent installing the latest 3.4.1 version of gl-matrix, which is causing install problems for users.
I think these are all the modules that require `gl-matrix`.
=> Pin gl-matrix to ~3.3.0

modules/core/tsconfig.json, modules/culling/tsconfig.json, modules/geoid/package.json, modules/geoid/tsconfig.json, modules/geospatial/tsconfig.json, modules/main/tsconfig.json, modules/polygon/tsconfig.json, modules/proj4/tsconfig.json, modules/sun/tsconfig.json, modules/web-mercator/tsconfig.json, package.json, tsconfig.build.json, tsconfig.modules.json, yarn.lock
- Adds new tsbuild and tsclean scripts but does not yet replace the ocular build.
=> chore: Add typescript monorepo build setup

modules/web-mercator/src/fit-bounds.ts, modules/web-mercator/src/index.ts, modules/web-mercator/src/math-utils.ts, modules/web-mercator/src/web-mercator-utils.ts, modules/web-mercator/test/spec/fit-bounds.spec.js, modules/web-mercator/test/spec/fly-to-viewport.spec.js, modules/web-mercator/test/utils/test-utils.js
Fix `fitBounds` crash when bounds contain extreme latitudes. (trying to unproject `Infinity`)
=> [web-mercator] fitBounds respects Web Mercator bounds

modules/web-mercator/src/index.ts, modules/web-mercator/src/web-mercator-utils.ts
A more efficient function to replace
`getDistanceScales({longitude, latitude}).unitsPerMeter`
Moving here from deck's WebMercatorViewport
=> Add unitsPerMeter util

docs/whats-new.md, modules/polygon/docs/api-reference/earcut.md, modules/polygon/docs/api-reference/polygon-utils.md, modules/polygon/src/earcut.ts, modules/polygon/src/polygon-utils.ts, modules/polygon/test/earcut.spec.ts
Incorporate features from https://github.com/visgl/deck.gl/pull/7205 but without mutating the positions array.
Also use permissive typing (`number[]` -> `NumericArray`) so that deck.gl can call this function directly.
=> [polygon] Add plane option to earcut

modules/core/src/classes/euler.ts
This was fixed some time back but appears to have regressed.
=> Fixed indexing for accessing rotation order in Euler.getQuaternion
