- src/vector.js
- test/lib/vector3.spec.js
> Fix Vector.len and Vector.dot

- src/matrix4.js
- test/lib/common.spec.js
- test/lib/matrix4.spec.js
- test/lib/vector3.spec.js
> Fix Matrix4.rotateAxis. Add rotation unit tests.

- .babelrc
- aliases.js
- package.json
- src/lib/assert.js
- src/matrix4.js
- src/spherical-coordinates.js
- test/size/import-nothing.js
- test/webpack.config.js
- yarn.lock
Back porting 1.1 changes on master to 1.0-release branch
> Remove external assert. Add babel-minify.

- src/matrix4.js
row index and column index are swapped because of column major matrix issue
> fix matrix column bug

- src/lib/common.js
- test/src/common.spec.js
Use local `isArray` to include `Array`s and `TypedArray`s.
> use correct isArray

- src/quaternion.js
This PR resolves the issue mentioned in #32.
> Fix quaternion multiply (multiplying by undefined)

- test/src/pose.spec.js
Based on @twojtasz commmit f014aca
> Test coordinate transforms between poses

- docs/api-reference/matrix3.md
- src/index.js
- src/lib/validators.js
- src/matrix3.js
- src/matrix4.js
- test/size/matrix3.js
- test/src/index.js
- test/src/matrix3.spec.js
- implement APIs in matrix3 class
- add test cases
- add doc
> Implement matrix3

- src/matrix3.js
- src/matrix4.js
- test/src/matrix3.spec.js
- test/src/matrix4.spec.js
- yarn.lock
The API documentation mentions the following: 
https://github.com/uber-web/math.gl/blob/master/docs/api-reference/matrix3.md#scale
https://github.com/uber-web/math.gl/blob/master/docs/api-reference/matrix4.md#scale
This PR resolves the issue mentioned in #40 and implements the functionality for both Matrix3 and Matrix4.
> Add scale factor support to Matrix3 and Matrix4

- babel.config.js
- ocular-dev-tools.config.js
- package.json
- webpack.config.js
- yarn.lock
Add explicit babel and webpack config files.
> Upgrade ocular-dev-tools to 0.0.11

- README.md
Migrate build badge from travis-ci.org to travis-ci.com.  
Replace starveller badge with coveralls badge.
> Migrate build badge from travis-ci.org to travis-ci.com

- modules/viewport-mercator-project/docs/api-reference/web-mercator-utils.md
- modules/viewport-mercator-project/docs/developer-guide/offset-projection-accuracy.md
- modules/viewport-mercator-project/src/fit-bounds.js
- modules/viewport-mercator-project/src/fly-to-viewport.js
- modules/viewport-mercator-project/src/index.js
- modules/viewport-mercator-project/src/viewport.js
- modules/viewport-mercator-project/src/web-mercator-utils.js
- modules/viewport-mercator-project/src/web-mercator-viewport.js
- modules/viewport-mercator-project/test/fp32-limits.js
- modules/viewport-mercator-project/test/spec/web-mercator-utils.spec.js
For https://github.com/uber/deck.gl/issues/3831
> [viewport-mercator-project] use zoom-independent world space

- modules/core/src/lib/common.js
- modules/core/test/lib/common.spec.js
> Fix equals bug

- modules-legacy/viewport-mercator-project/module.js
- modules-legacy/viewport-mercator-project/package.json
- modules-legacy/viewport-mercator-project/src/README.md
As a wrapper for `@math.gl/web-mercator`
> viewport-mercator-project@7.0.0

- modules/culling/src/lib/culling-volume.js
- modules/culling/src/lib/perspective-off-center-frustum.js
- modules/culling/src/lib/plane.js
- modules/culling/test/lib/culling-volume.spec.js
- Fix all the places where planes are defined as Vector4
- Restore disabled tests
> Fix various culling issues

- modules/web-mercator/docs/api-reference/web-mercator-viewport.md
Fix errors, use consistent language with react-map-gl and deck.gl
> Update WebMercatorViewport documentation

- .travis.yml
- babel.config.js
- examples/benchmarks/bench-results.js
- modules/core/src/classes/base/math-array.js
- modules/core/src/classes/base/vector.js
- modules/core/src/classes/euler.js
- modules/core/src/classes/matrix3.js
- modules/core/src/classes/matrix4.js
- modules/core/src/classes/pose.js
- modules/core/src/classes/quaternion.js
- modules/core/src/classes/spherical-coordinates.js
- modules/core/src/classes/vector2.js
- modules/core/src/classes/vector3.js
- modules/core/src/classes/vector4.js
- modules/core/src/index.js
- modules/core/src/lib/common.js
- modules/core/src/lib/validators.js
- package.json
- tsconfig.json
- yarn.lock
> "soft" typescript checking of core module

- modules/core/src/addons/polygon.d.ts
The second argument of the SegmentVisitor type should be number[] instead of number as it is a point.
> Update SegmentVisitor in polygon.d.ts

- docs/README.md
- docs/table-of-contents.json
- docs/whats-new.md
- modules/geospatial/docs/developer-guide/geospatial-guide.md
- modules/proj4/README.md
- modules/proj4/docs/api-reference/proj4-projection.md
- modules/proj4/docs/developer-guide/proj4-guide.md
- modules/proj4/package.json
- modules/proj4/src/index.d.ts
- modules/proj4/src/index.js
- modules/proj4/src/lib/proj4-projection.d.ts
- modules/proj4/src/lib/proj4-projection.js
- modules/proj4/test/index.js
- modules/proj4/test/lib/proj4-projection.spec.js
- modules/proj4/test/lib/test-data.js
- modules/sun/test/suncalc.spec.js
- test/modules.spec.js
- yarn.lock
A light wrapper around `proj4` for general CRS to CRS conversion.
> proj4: new module for coordinate system conversion

- docs/table-of-contents.json
- modules/core/docs/api-reference/spherical-coordinates.md
- website/gatsby-config.js
- website/package.json
Already deployed, see https://math.gl/docs/whats-new
> website updates

- modules/web-mercator/docs/api-reference/web-mercator-viewport.md
Follow up of https://github.com/uber-web/math.gl/pull/170
> Fix WebMercatorViewport doc formatting

- modules/polygon/src/cut-by-grid.js
Signed-off-by: Shan He <heshan0131@gmail.com>
> [Perf] replace concat to improve cutPolygonByGrid performance

- README.md
- docs/README.md
- docs/whats-new.md
- modules/geospatial/docs/README.md
- modules/web-mercator/docs/README.md
Cleaning up the docs, prepping for a new module.
> Documentation Pass

- modules/core/package.json
- modules/culling/package.json
- modules/geoid/package.json
- modules/geospatial/package.json
- modules/proj4/package.json
- modules/sun/package.json
- modules/web-mercator/package.json
- package.json
- yarn.lock
Issue with mjs files, webpack and babel/runtime.
See https://github.com/babel/babel/issues/12169
> Bump babel/runtime version to fix mjs issue

- modules/core/docs/api-reference/matrix4.md
- modules/core/docs/developer-guide/transformations.md
Fixes #195.  Not sure what the ["caveats"](https://github.com/uber-web/math.gl/pull/196/files#diff-289aefc06ed210de481ada54f9e6861a43f5aadba682aa1c4d40406adbba8945R111) exactly were or how you want to phrase them.  I guessed invertibility but am not sure so didn't write anything.  Would love feedback and can always add things if you want something more comprehensive
> Transformation docs

- .eslintignore
- package.json
- yarn.lock
> Update build targets

- modules/core/package.json
- modules/culling/package.json
- modules/geoid/package.json
- modules/geospatial/package.json
- modules/main/package.json
- modules/polygon/package.json
- modules/proj4/package.json
- modules/sun/package.json
- modules/web-mercator/package.json
> Drop ES6 entry points from package.json

- modules/polygon/src/polygon-utils.js
- modules/polygon/test/bench.js
- modules/polygon/test/polygon.spec.js
- modules/polygon/test/utils.js
Implements https://github.com/uber-web/math.gl/issues/212
> Faster polygon area

- modules/web-mercator/src/index.js
Required by deck.gl: https://github.com/visgl/deck.gl/pull/5930#discussion_r671415317
> Export altitudeToFovy & fovyToAltitude

- modules/core/src/classes/euler.js
Fixes #109 i think it is just typo in your code
> fixed Euler.getQuaternion never use rotation order

- modules/core/package.json
> Fix core package types entry point

- modules/sun/src/suncalc.ts
- modules/sun/test/suncalc.spec.js
Bring in the fix and tests from https://github.com/visgl/deck.gl/pull/5393
> [sun] Fix position calculation

- modules/culling/src/constants.ts
- modules/culling/src/lib/bounding-volumes/axis-aligned-bounding-box.ts
- modules/culling/src/lib/bounding-volumes/bounding-sphere.ts
- modules/culling/src/lib/bounding-volumes/bounding-volume.ts
- modules/culling/src/lib/bounding-volumes/oriented-bounding-box.ts
- modules/culling/src/lib/culling-volume.ts
- modules/polygon/src/polygon-utils.ts
- modules/polygon/test/bench.js
- package.json
- tsconfig.build.json
- yarn.lock
> Remove enum exports

- modules/web-mercator/src/fit-bounds.ts
- modules/web-mercator/test/spec/fit-bounds.spec.js
Fixes https://github.com/uber-web/math.gl/issues/301
> [@math.gl/web-mercator] Fix reverse top/bottom padding in fitBounds
